config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheet_details
  resources :expenses
  resources :tickets
  resources :licenses
  devise_for :users

  root to: 'dashboard#index'
  resources :spreadsheets do
    resources :spreadsheet_details
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spreadsheet_detail.rb
# == Schema Information
#
# Table name: spreadsheet_details
#
#  id             :integer          not null, primary key
#  spreadsheet_id :integer
#  totalv         :decimal(8, 2)
#  netov          :decimal(8, 2)
#  gastov         :decimal(8, 2)
#  choferv        :decimal(8, 2)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class SpreadsheetDetail < ApplicationRecord
belongs_to :Spreadsheet
belongs_to :Tickets

accepts_nested_attributes_for :item




end

app/controllers/spreadsheet_details_controller.rb
class SpreadsheetDetailsController < ApplicationController
  before_action :set_spreadsheet_detail, only: [:show, :edit, :update, :destroy]

  # GET /spreadsheet_details
  # GET /spreadsheet_details.json
  def index
    @spreadsheet_details = SpreadsheetDetail.all
  end

  # GET /spreadsheet_details/1
  # GET /spreadsheet_details/1.json
  def show
  end

  # GET /spreadsheet_details/new
  def new
    @spreadsheet_detail = SpreadsheetDetail.new
  end

  # GET /spreadsheet_details/1/edit
  def edit
  end

  # POST /spreadsheet_details
  # POST /spreadsheet_details.json
  def create
    @spreadsheet_detail = SpreadsheetDetail.new(spreadsheet_detail_params)

    respond_to do |format|
      if @spreadsheet_detail.save
        format.html { redirect_to @spreadsheet_detail, notice: 'Spreadsheet detail was successfully created.' }
        format.json { render :show, status: :created, location: @spreadsheet_detail }
      else
        format.html { render :new }
        format.json { render json: @spreadsheet_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spreadsheet_details/1
  # PATCH/PUT /spreadsheet_details/1.json
  def update
    respond_to do |format|
      if @spreadsheet_detail.update(spreadsheet_detail_params)
        format.html { redirect_to @spreadsheet_detail, notice: 'Spreadsheet detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @spreadsheet_detail }
      else
        format.html { render :edit }
        format.json { render json: @spreadsheet_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spreadsheet_details/1
  # DELETE /spreadsheet_details/1.json
  def destroy
    @spreadsheet_detail.destroy
    respond_to do |format|
      format.html { redirect_to spreadsheet_details_url, notice: 'Spreadsheet detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spreadsheet_detail
      @spreadsheet_detail = SpreadsheetDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spreadsheet_detail_params
      params.require(:spreadsheet_detail).permit(:spreadsheet_id, :totalv, :netov, :gastov, :choferv)
    end
end

app/helpers/spreadsheet_details_helper.rb
module SpreadsheetDetailsHelper
end

app/views/spreadsheet_details/_form.html.erb
<%= form_with(model: spreadsheet_detail, local: true) do |form| %>
  <% if spreadsheet_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spreadsheet_detail.errors.count, "error") %> prohibited this spreadsheet_detail from being saved:</h2>

      <ul>
      <% spreadsheet_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spreadsheet_id %>
    <%= form.number_field :spreadsheet_id %>
  </div>

  <div class="field">
    <%= form.label :totalv %>
    <%= form.text_field :totalv %>
  </div>

  <div class="field">
    <%= form.label :netov %>
    <%= form.text_field :netov %>
  </div>

  <div class="field">
    <%= form.label :gastov %>
    <%= form.text_field :gastov %>
  </div>

  <div class="field">
    <%= form.label :choferv %>
    <%= form.text_field :choferv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spreadsheet_details/edit.html.erb
<h1>Editing Spreadsheet Detail</h1>

<%= render 'form', spreadsheet_detail: @spreadsheet_detail %>

<%= link_to 'Show', @spreadsheet_detail %> |
<%= link_to 'Back', spreadsheet_details_path %>

app/views/spreadsheet_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spreadsheet Details</h1>

<table>
  <thead>
    <tr>
      <th>Spreadsheet</th>
      <th>Totalv</th>
      <th>Netov</th>
      <th>Gastov</th>
      <th>Choferv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spreadsheet_details.each do |spreadsheet_detail| %>
      <tr>
        <td><%= spreadsheet_detail.spreadsheet_id %></td>
        <td><%= spreadsheet_detail.totalv %></td>
        <td><%= spreadsheet_detail.netov %></td>
        <td><%= spreadsheet_detail.gastov %></td>
        <td><%= spreadsheet_detail.choferv %></td>
        <td><%= link_to 'Show', spreadsheet_detail %></td>
        <td><%= link_to 'Edit', edit_spreadsheet_detail_path(spreadsheet_detail) %></td>
        <td><%= link_to 'Destroy', spreadsheet_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spreadsheet Detail', new_spreadsheet_detail_path %>

app/views/spreadsheet_details/new.html.erb
<h1>New Spreadsheet Detail</h1>

<%= render 'form', spreadsheet_detail: @spreadsheet_detail %>

<%= link_to 'Back', spreadsheet_details_path %>

app/views/spreadsheet_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spreadsheet:</strong>
  <%= @spreadsheet_detail.spreadsheet_id %>
</p>

<p>
  <strong>Totalv:</strong>
  <%= @spreadsheet_detail.totalv %>
</p>

<p>
  <strong>Netov:</strong>
  <%= @spreadsheet_detail.netov %>
</p>

<p>
  <strong>Gastov:</strong>
  <%= @spreadsheet_detail.gastov %>
</p>

<p>
  <strong>Choferv:</strong>
  <%= @spreadsheet_detail.choferv %>
</p>

<%= link_to 'Edit', edit_spreadsheet_detail_path(@spreadsheet_detail) %> |
<%= link_to 'Back', spreadsheet_details_path %>