config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheet_details
  resources :expenses
  resources :tickets
  resources :licenses
  devise_for :users

  root to: 'dashboard#index'
  resources :spreadsheets do
    resources :spreadsheet_details
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id         :integer          not null, primary key
#  license_id :integer
#  code       :string
#  totalvt    :decimal(8, 2)
#  netov      :decimal(8, 2)
#  gastov     :decimal(8, 2)
#  choferv    :decimal(8, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ticket < ApplicationRecord
  belongs_to :license
  belongs_to :spreadsheet
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  #before_action :set_combo_values, only: [:new, :edit]
  PAGE_SIZE = 10

  # GET /tickets
  # GET /tickets.json
  def index
    @page = (params[:page] || 0).to_i
    @tickets = Ticket.all

    if params[:keywords].present?
         @keywords = params[:keywords]
         @tickets = Ticket.where("lower(name) LIKE '%#{@keywords.downcase}%'").order(:name)
                        .offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
         number_of_records = Ticket.where("lower(name) LIKE '%#{@keywords.downcase}%'").count
       else
         @brands = Ticket.order(:name).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
         number_of_records = Ticket.count
       end
       @number_of_pages = (number_of_records % PAGE_SIZE) == 0 ?
                           number_of_records / PAGE_SIZE - 1 : number_of_records / PAGE_SIZE

  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show

  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
  
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:license_id, :code, :totalvt, :netov, :gastov, :choferv)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :license_id %>
    <%= form.text_field :license_id %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :totalvt %>
    <%= form.text_field :totalvt %>
  </div>

  <div class="field">
    <%= form.label :netov %>
    <%= form.text_field :netov %>
  </div>

  <div class="field">
    <%= form.label :gastov %>
    <%= form.text_field :gastov %>
  </div>

  <div class="field">
    <%= form.label :choferv %>
    <%= form.text_field :choferv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						items_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						items_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/tickets/_result_search.html.erb
<table class="table">
 <thead>
  <tr>
   <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
  </tr>
  <tr>
   <th>Nombre</th>
   <th>Fecha de Creacion</th>
   <th>Fecha de Modificación</th>
   <th colspan="2"></th>
  </tr>
 </thead>

 <tbody>
  <div id="brands">
   <% @tickets.each do |ticket| %>
    <tr>
     <td><%= ticket.number %></td>
     <td><%= ticket.created_at.strftime("%d/%m/%Y") %></td>
     <td><%= ticket.updated_at.strftime("%d/%m/%Y") %></td>
     <td>
      <%= button_to edit_ticket_path(ticket), {method: :get, class: "btn btn-info"} do %>
       <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
      <% end %>
     </td>
     <td>
      <%= button_to ticket, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
       <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
      <% end %>
     </td>
    </tr>
   <% end %>
  </div>
 </tbody>
</table>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<div class="panel panel-default">
 <div class="panel-heading">Tickets</div>
 <div class="panel-body">
  <%= render partial: 'layouts/search_form', locals: { search_entity: 'tickets', word: "Ticket" } %>
  <br>
  <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
   <p>
    <%= button_to new_ticket_path, {method: :get, class: "btn btn-success"} do %>
     <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nuevo Ticket
    <% end %>
   </p>
  </div>
 </div>
 <%= render partial: 'result_search' %>
</div>

app/views/tickets/new.html.erb
<div class="container-fluid">
 <div class="row">
   <h1>New Ticket</h1>


  <%= render 'form', ticket: @ticket %>

  <%= link_to 'Volver', tickets_path %>
 </div>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License:</strong>
  <%= @ticket.license %>
</p>

<p>
  <strong>Code:</strong>
  <%= @ticket.code %>
</p>

<p>
  <strong>Totalvt:</strong>
  <%= @ticket.totalvt %>
</p>

<p>
  <strong>Netov:</strong>
  <%= @ticket.netov %>
</p>

<p>
  <strong>Gastov:</strong>
  <%= @ticket.gastov %>
</p>

<p>
  <strong>Choferv:</strong>
  <%= @ticket.choferv %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>