config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheet_details
  resources :expenses
  resources :tickets
  resources :licenses
  devise_for :users

  root to: 'dashboard#index'
  resources :spreadsheets do
    resources :spreadsheet_details
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spreadsheet.rb
# == Schema Information
#
# Table name: spreadsheets
#
#  id         :integer          not null, primary key
#  number     :integer
#  date       :date
#  state      :integer
#  tneto      :decimal(8, 2)
#  tgastog    :decimal(8, 2)
#  tapagar    :decimal(8, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Spreadsheet < ApplicationRecord
has_many :spreadsheets_details, inverse_of: :Spreadsheet, dependent: :destroy
has_many :tickets, through: :spreadsheets_details
belongs_to :user
validates :number, presence: true
validates :date, presence: true

	accepts_nested_attributes_for :spreadsheet_detail, reject_if: :spreadsheet_detail_rejectable?, allow_destroy: accepts_nested_attributes_for

enum state: [:draft, :confirmed]



end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :set_spreadsheet, only: [:show, :edit, :update, :destroy]

  # GET /spreadsheets
  # GET /spreadsheets.json
  def index
    @spreadsheets = Spreadsheet.all.order("created_at DESC")
  end

  # GET /spreadsheets/1
  # GET /spreadsheets/1.json
  def show
    @spreadsheet =Spreadsheet.find(params[:id])
  #  @ticket =Ticket.new(:spreadsheet=> @spreadsheet)
  end

  # GET /spreadsheets/new
  def new
    @spreadsheet = Spreadsheet.new
  end

  # GET /spreadsheets/1/edit
  def edit
  end

  # POST /spreadsheets
  # POST /spreadsheets.json
  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)

    respond_to do |format|
      if @spreadsheet.save
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.' }
        format.json { render :show, status: :created, location: @spreadsheet }
      else
        format.html { render :new }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spreadsheets/1
  # PATCH/PUT /spreadsheets/1.json
  def update
    respond_to do |format|
      if @spreadsheet.update(spreadsheet_params)
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @spreadsheet }
      else
        format.html { render :edit }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spreadsheets/1
  # DELETE /spreadsheets/1.json
  def destroy
    @spreadsheet.destroy
    respond_to do |format|
      format.html { redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spreadsheet
      @spreadsheet = Spreadsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spreadsheet_params
      params.require(:spreadsheet).permit(:number, :date, :state, :tneto, :tgastog, :tapagar)
    end
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/spreadsheets/_form.html.erb
<%= form_with(model: spreadsheet, local: true) do |form| %>
  <% if spreadsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spreadsheet.errors.count, "error") %> prohibited this spreadsheet from being saved:</h2>

      <ul>
      <% spreadsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.number_field :state %>
  </div>

  <div class="field">
    <%= form.label :tneto %>
    <%= form.text_field :tneto %>
  </div>

  <div class="field">
    <%= form.label :tgastog %>
    <%= form.text_field :tgastog %>
  </div>

  <div class="field">
    <%= form.label :tapagar %>
    <%= form.text_field :tapagar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spreadsheets/edit.html.erb
<h1>Editing Spreadsheet</h1>

<%= render 'form', spreadsheet: @spreadsheet %>

<%= link_to 'Show', @spreadsheet %> |
<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spreadsheets</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th>State</th>
      <th>Tneto</th>
      <th>Tgastog</th>
      <th>Tapagar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spreadsheets.each do |spreadsheet| %>
      <tr>
        <td><%= spreadsheet.number %></td>
        <td><%= spreadsheet.date %></td>
        <td><%= spreadsheet.state %></td>
        <td><%= spreadsheet.tneto %></td>
        <td><%= spreadsheet.tgastog %></td>
        <td><%= spreadsheet.tapagar %></td>
        <td><%= link_to 'Show', spreadsheet %></td>
        <td><%= link_to 'Edit', edit_spreadsheet_path(spreadsheet) %></td>
        <td><%= link_to 'Destroy', spreadsheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spreadsheet', new_spreadsheet_path %>

app/views/spreadsheets/new.html.erb
<h1>New Spreadsheet</h1>

<%= render 'form', spreadsheet: @spreadsheet %>

<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @spreadsheet.number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @spreadsheet.date %>
</p>

<p>
  <strong>State:</strong>
  <%= @spreadsheet.state %>
</p>

<p>
  <strong>Tneto:</strong>
  <%= @spreadsheet.tneto %>
</p>

<p>
  <strong>Tgastog:</strong>
  <%= @spreadsheet.tgastog %>
</p>

<p>
  <strong>Tapagar:</strong>
  <%= @spreadsheet.tapagar %>
</p>

<%= link_to 'Edit', edit_spreadsheet_path(@spreadsheet) %> |
<%= link_to 'Back', spreadsheets_path %>